from database import DB
from numpy import array
import matplotlib
import psycopg2
import sqlite3

# Gui Starts here
# Use sqlite to generate an "defaults" database
# Automatically detect standard kplr filenames
# Scan for previously undetected files
    # Request permission to insert
# Generate X, Y Menus
# Checkbox to indicate custom bounds
    # If unchecked, autogenerated boundaries
# Checkboxes for types of data smooth
    ## Wish list V
    # Prompt to save smooth data / Is space more important than speed?

# Plot Variables